### ISSUE TITLE
SVG Badge Image Adjustments Per Criteria

### ISSUE THREAD

**Issue by kayaelle** [OpenWorksGroup/Open-BadgeBot#3]
Every time criteria is submitted successfully, the badge is earned and the svg associated with that criteria is added to the badge image.

**Comment by zwallacedev** [comment]
For Thursday's presentation, I think we take this very easy and we have as many badges as we have criterion. For the number of criteria that they complete, they get the associated badge. For the future, I think it would be cool to have some sort of transformation applied to an SVG as described in http://tutorials.jenkov.com/svg/svg-transformation.html.

**Comment by zwallacedev** [comment]
Currently attempting to figure out how to add a `rect` to an existing SVG file. I've found a few plugins that I'm considering, but its possible we will have to fake a dom using `jsdom` before we are able to edit the SVG. This will need more thought, but I wanted to leave some notes.

Fun little SVG editor: https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_rect2

My initial thought on how this is going to work:
1) Read the SVG file via either `fs` or `xmlhttprequest`
2) Place the SVG in some sort of javascript object (this is where we may need to fake a dom)
3) Create rects based on how many of the criteria they've completed. (One rect for each criteria)
4) Randomly assign colors to each rect
5) Append rects to the SVG
6) Use our converter to transform into a PNG
7) Send to twitter via our method

**Comment by zwallacedev** [comment]
Banging my head against the wall, I need to take a break. Here is my train of thought on reading the SVG file, creating a javascript object that can be modified, and outputting a PNG file.
1) Initiate SVG.js, which should create a blank svg for us to use
2) Draw our existing svg onto the blank svg
3) convert the newly drawn svg (via `blankSvg.svg()`) to a png with a new `localConvert` method.
Once we can get these three steps working, it seems like SVG.js will be pretty easy to add a few `rect`s into our new blankSvg.

**Comment by zwallacedev** [comment]
Fixed in #26
